// Staging the game into the runtime's filesystem.
//
// The loader mounts the origin private filesystem at /libsdl and then works
// entirely in terms of native paths: it reads /libsdl/Celeste.exe, writes the
// patched assembly to /libsdl/CustomCeleste.dll, and symlinks /Content at
// /libsdl/Content so FNA finds the game's assets where it expects them.
//
// So OPFS *is* the game directory. Everything here is about getting the
// player's files into it — from a zip, from a directory they picked, or from a
// previous session that already has them — and taking them back out again.

import { ZipReader, type ZipEntry } from './celeste.zip.js';

/** Where the loader mounts OPFS. Paths below are relative to this. */
export const VFS_ROOT = '/libsdl';

/**
 * How many files staging has in flight at once.
 *
 * Every OPFS operation is an async round trip, and a Celeste install is ~1,240
 * files — so a strictly sequential copy spends most of its wall clock waiting
 * rather than moving bytes. Eight lanes is enough to keep the storage backend
 * busy without putting eight large inflate streams on the heap at once; the
 * streams are backpressured, so what is resident is a few chunks per lane and
 * not a few files.
 */
export const STAGE_CONCURRENCY = 8;

/**
 * Put a path inside the runtime's storage namespace.
 *
 * Upstream's loader has no namespace: it reads and writes absolute paths under
 * the mount, and the mount is the origin's OPFS root, so Celeste claims
 * top-level names for the whole origin. A runtime built from source here is
 * patched to take one (`scripts/patch-loader-source.mjs`), and it is a *pure
 * prefix* of the layout without it — so everything this package knows about
 * storage stays a single set of constants, and this is the only place the
 * difference shows up.
 *
 * An empty namespace is the stock layout, which is what a downloaded runtime
 * has.
 */
export function inNamespace(namespace: string, path: string): string {
  if (!namespace) return path;
  return path ? `${namespace}/${path}` : namespace;
}

/** The Everest build, read by `Patcher.ExtractEverest()`. */
export const EVEREST_ZIP = 'everest.zip';

/** Where that zip is unpacked to, and where the patcher looks for the loader. */
export const EVEREST_DIR = 'Celeste/Everest';

/** Marker file inside `EVEREST_DIR` that says the loader is unpacked. */
export const EVEREST_MARKER = `${EVEREST_DIR}/Celeste.Mod.mm.dll`;

/** MonoMod's output: the game, patched for WebAssembly (and for Everest). */
export const PATCHED_ASSEMBLY = 'CustomCeleste.dll';

/**
 * The other two assemblies the patcher drops at the root.
 *
 * Not obvious from anything this package writes — they are hardcoded paths
 * inside `CelesteLoader.dll` (`/libsdl/MMHOOK_Celeste.dll` and
 * `/libsdl/Celeste.Mod.mm.dll`), so they appear in storage without the SDK ever
 * naming them. Both are regenerated by a patch, so purging and archiving both
 * have to know they are derived rather than the player's.
 */
export const PATCHER_ASSEMBLIES: readonly string[] = ['MMHOOK_Celeste.dll', 'Celeste.Mod.mm.dll'];

/** Directories the loader creates on mount; mods and saves persist in them. */
export const MODS_DIR = 'Celeste/Mods';
export const SAVES_DIR = 'Celeste/Saves';

/**
 * Where the SDK records which top-level entries it put in storage.
 *
 * A Celeste install is whatever the player's folder held — 25 top-level entries
 * for a vanilla one, mostly assemblies this package cannot name in advance — so
 * purging by a fixed list leaves most of it behind, and purging by "everything
 * at the root" would take anything sharing the origin with it. Recording what
 * was actually claimed is the only way to remove exactly that.
 *
 * It lives under `Celeste/`, which this package already owns, so keeping the
 * record does not itself claim another name at the root.
 */
export const STAGED_MANIFEST = 'Celeste/staged.json';

/** `navigator.storage.getDirectory()`, with a readable failure. */
export async function opfsRoot(): Promise<FileSystemDirectoryHandle> {
  if (typeof navigator === 'undefined' || !navigator.storage?.getDirectory) {
    throw new Error(
      'celeste: this browser has no origin private filesystem, which is where the game is staged',
    );
  }
  return navigator.storage.getDirectory();
}

/** Async iteration over a directory, which lib.dom does not always type. */
type IterableDirectory = FileSystemDirectoryHandle & {
  entries(): AsyncIterableIterator<[string, FileSystemHandle]>;
};

function splitPath(path: string): string[] {
  return path.split('/').filter(Boolean);
}

/** `mkdir -p`, returning the leaf. */
export async function ensureDirectory(
  root: FileSystemDirectoryHandle,
  path: string,
): Promise<FileSystemDirectoryHandle> {
  let handle = root;
  for (const segment of splitPath(path)) {
    handle = await handle.getDirectoryHandle(segment, { create: true });
  }
  return handle;
}

async function directoryOf(
  root: FileSystemDirectoryHandle,
  path: string,
  create: boolean,
): Promise<FileSystemDirectoryHandle | null> {
  let handle = root;
  for (const segment of splitPath(path)) {
    try {
      handle = await handle.getDirectoryHandle(segment, { create });
    } catch {
      return null;
    }
  }
  return handle;
}

/**
 * `mkdir -p`, memoised, for the one caller that does it thousands of times.
 *
 * `writeFile` resolves a path from the root a segment at a time, and each of
 * those segments is its own async round trip. Staging puts ~1,240 files into
 * ~90 directories, so the unmemoised version re-resolves
 * `Content/Graphics/Atlases` once per file inside it — thousands of round trips
 * to reach handles that never change.
 *
 * The *promise* is what gets cached, not the handle: lanes running in parallel
 * ask for the same directory at the same time, and caching the promise makes
 * them share the one lookup instead of racing to create it.
 */
class DirectoryIndex {
  private readonly cache = new Map<string, Promise<FileSystemDirectoryHandle>>();

  constructor(private readonly root: FileSystemDirectoryHandle) {}

  directory(path: string): Promise<FileSystemDirectoryHandle> {
    const key = splitPath(path).join('/');
    if (!key) return Promise.resolve(this.root);

    let pending = this.cache.get(key);
    if (!pending) {
      const at = key.lastIndexOf('/');
      pending = this.directory(at < 0 ? '' : key.slice(0, at)).then((parent) =>
        parent.getDirectoryHandle(key.slice(at + 1), { create: true }),
      );
      this.cache.set(key, pending);
    }
    return pending;
  }

  async file(path: string): Promise<FileSystemFileHandle> {
    const segments = splitPath(path);
    const name = segments.pop();
    if (!name) throw new Error(`celeste: "${path}" is not a file path`);
    const parent = await this.directory(segments.join('/'));
    return parent.getFileHandle(name, { create: true });
  }
}

/**
 * `createSyncAccessHandle`, which lib.dom does not have because it only exists
 * in a worker — the whole reason `celeste.stage.worker.ts` exists.
 */
interface SyncAccessHandle {
  /**
   * Narrower than the real signature, which takes any `BufferSource`. Every
   * chunk reaching it here is a `Uint8Array`, and saying so avoids the
   * SharedArrayBuffer mismatch `createWritable` runs into below.
   */
  write(data: Uint8Array, options?: { at?: number }): number;
  truncate(size: number): void;
  flush(): void;
  close(): void;
}

type SyncCapableFileHandle = FileSystemFileHandle & {
  createSyncAccessHandle?: () => Promise<SyncAccessHandle>;
};

/** Bytes, or a stream of them, produced only once the destination is open. */
type Contents = Uint8Array | ReadableStream<Uint8Array>;

async function drain(
  contents: Contents,
  onChunk: (chunk: Uint8Array) => void | Promise<void>,
): Promise<void> {
  if (contents instanceof Uint8Array) return void (await onChunk(contents));

  const reader = contents.getReader();
  for (;;) {
    const { done, value } = await reader.read();
    if (done) return;
    if (value) await onChunk(value);
  }
}

/**
 * Write to an already-resolved file handle, by whichever route this realm has.
 *
 * `createWritable` is the only one the main thread gets, and it is the slow
 * one: Chrome writes through a temporary swap file and renames it into place on
 * `close()`, so every file costs roughly twice the I/O plus a rename. In a
 * worker the same handle also offers `createSyncAccessHandle`, which writes
 * into the file itself — which is why staging tries to run there.
 *
 * `contents` is a thunk because the sync handle can refuse to open (the file is
 * locked by another writer) and the fallback then has to ask for the bytes from
 * the start. Producing them only after a destination is open keeps that honest:
 * nothing is read until something is ready to receive it.
 *
 * The two routes differ in what a failure leaves behind: an unclosed writable
 * discards its swap file and the original survives, while the sync handle has
 * been writing into the file itself and leaves it short. That is the case
 * `copyDirectoryInto` resumes from — a file at the wrong size is rewritten — so
 * the difference costs a re-copy of one file rather than a corrupt install.
 */
async function writeContents(
  handle: FileSystemFileHandle,
  contents: () => Contents | Promise<Contents>,
): Promise<void> {
  const openSync = (handle as SyncCapableFileHandle).createSyncAccessHandle;
  if (openSync) {
    let access: SyncAccessHandle | null = null;
    try {
      access = await openSync.call(handle);
    } catch {
      // Locked, or not an OPFS file after all. The writable below works either
      // way, so this is a slow path rather than a failure.
    }

    if (access) {
      const sync = access;
      try {
        // The file may already hold a longer version of itself — a resumed copy
        // reaches here precisely when what is there is the wrong length.
        sync.truncate(0);
        let at = 0;
        await drain(await contents(), (chunk) => {
          at += sync.write(chunk, { at });
        });
        sync.flush();
      } finally {
        sync.close();
      }
      return;
    }
  }

  const writable = await handle.createWritable();
  const data = await contents();

  if (data instanceof Uint8Array) {
    // A `Uint8Array` over a SharedArrayBuffer is still a valid write chunk;
    // lib.dom's signature just does not say so.
    await writable.write(data as BufferSource);
    await writable.close();
    return;
  }

  // Piping keeps a 200 MB asset off the heap: it lands in storage a chunk at a
  // time, straight out of the inflate stream.
  await data.pipeTo(writable);
}

/** Write a file, creating its parent directories. */
export async function writeFile(
  root: FileSystemDirectoryHandle,
  path: string,
  data: Uint8Array | ReadableStream<Uint8Array>,
): Promise<void> {
  await writeContents(await new DirectoryIndex(root).file(path), () => data);
}

/**
 * Run `task` over `items` with `limit` of them in flight.
 *
 * Lanes pull from a shared cursor rather than being handed a slice each, so one
 * slow file does not leave a lane idle while another still has work queued. The
 * first failure stops the rest: staging that has started failing has no reason
 * to keep writing, and the error the caller sees should be the one that
 * actually happened first.
 */
async function pooled<T>(
  items: readonly T[],
  limit: number,
  task: (item: T) => Promise<void>,
): Promise<void> {
  let cursor = 0;
  let failure: unknown = null;

  const lane = async (): Promise<void> => {
    for (let at = cursor++; at < items.length; at = cursor++) {
      if (failure !== null) return;
      try {
        await task(items[at]!);
      } catch (error) {
        failure ??= error;
        return;
      }
    }
  };

  await Promise.all(Array.from({ length: Math.min(limit, items.length) }, lane));
  if (failure !== null) throw failure;
}

export async function readFile(
  root: FileSystemDirectoryHandle,
  path: string,
): Promise<Uint8Array | null> {
  const segments = splitPath(path);
  const name = segments.pop();
  if (!name) return null;

  const parent = await directoryOf(root, segments.join('/'), false);
  if (!parent) return null;
  try {
    const handle = await parent.getFileHandle(name, { create: false });
    return new Uint8Array(await (await handle.getFile()).arrayBuffer());
  } catch {
    return null;
  }
}

export async function exists(root: FileSystemDirectoryHandle, path: string): Promise<boolean> {
  const segments = splitPath(path);
  const name = segments.pop();
  if (!name) return true;

  const parent = await directoryOf(root, segments.join('/'), false);
  if (!parent) return false;
  try {
    await parent.getFileHandle(name, { create: false });
    return true;
  } catch {
    // Not a file — it may still be a directory, which is what the install check
    // asks about for Content/Maps and friends.
  }
  try {
    await parent.getDirectoryHandle(name, { create: false });
    return true;
  } catch {
    return false;
  }
}

export interface ListOptions {
  /** Stop after this many entries. */
  limit?: number;
  /**
   * Do not descend past this many path segments.
   *
   * A caller that only needs the top of the tree should say so. Measured
   * against a vanilla install, stopping at 4 segments — as deep as the install
   * check ever looks — lists 209 entries where a full walk lists 1,289. Over
   * OPFS every one of those is an async round trip.
   */
  depth?: number;
}

/**
 * Every path under `path`, relative to it. Used to run the install check
 * against what actually made it into storage, and to decide whether a previous
 * session already staged the game.
 */
export async function listPaths(
  root: FileSystemDirectoryHandle,
  path = '',
  options: ListOptions = {},
): Promise<string[]> {
  const { limit = Infinity, depth = Infinity } = options;

  const start = await directoryOf(root, path, false);
  if (!start) return [];

  const out: string[] = [];
  const walk = async (
    handle: FileSystemDirectoryHandle,
    prefix: string,
    level: number,
  ): Promise<void> => {
    for await (const [name, entry] of (handle as IterableDirectory).entries()) {
      if (out.length >= limit) return;
      const child = prefix ? `${prefix}/${name}` : name;
      out.push(child);
      if (entry.kind === 'directory' && level < depth) {
        await walk(entry as FileSystemDirectoryHandle, child, level + 1);
      }
    }
  };

  await walk(start, '', 1);
  return out;
}

/** Remove a file or directory. Returns whether anything was there. */
export async function removePath(root: FileSystemDirectoryHandle, path: string): Promise<boolean> {
  const segments = splitPath(path);
  const name = segments.pop();
  if (!name) return false;

  const parent = await directoryOf(root, segments.join('/'), false);
  if (!parent) return false;
  try {
    await parent.removeEntry(name, { recursive: true });
    return true;
  } catch {
    return false;
  }
}

export interface StageProgress {
  /** Entries dealt with so far. Monotonic, but files finish out of order. */
  done: number;
  /** Entries to write in total. */
  total: number;
  /** Path of the entry that just finished. */
  path: string;
}

export interface ExtractOptions {
  /** Strip this prefix off every entry — the install root inside the archive. */
  strip?: string;
  /** Write entries under this path instead of at the root. */
  into?: string;
  /** Skip entries for which this returns false. */
  filter?: (path: string) => boolean;
  onProgress?: (progress: StageProgress) => void;
}

export interface CopyOptions {
  /** Skip files for which this returns false. Paths are relative to the source. */
  filter?: (path: string) => boolean;
  onProgress?: (progress: StageProgress) => void;
}

/**
 * Unpack an archive into storage.
 *
 * Entries are streamed through the inflater rather than read into memory,
 * because a Celeste install is ~1.3 GB and the browser will not hold it twice —
 * and `STAGE_CONCURRENCY` of them at a time, because one at a time is latency
 * bound long before it is bandwidth bound.
 */
export async function extractInto(
  reader: ZipReader,
  root: FileSystemDirectoryHandle,
  options: ExtractOptions = {},
): Promise<number> {
  const { strip = '', into = '', filter, onProgress } = options;

  const wanted = reader.entries.filter((entry: ZipEntry) => {
    if (entry.isDirectory) return false;
    if (strip && !entry.name.startsWith(strip)) return false;
    const relative = entry.name.slice(strip.length);
    // Zip entries are allowed to contain "..", and this writes into a directory
    // the game later executes code from.
    if (!relative || relative.split('/').includes('..')) return false;
    return filter ? filter(relative) : true;
  });

  const index = new DirectoryIndex(root);
  let done = 0;

  await pooled(wanted, STAGE_CONCURRENCY, async (entry) => {
    const relative = entry.name.slice(strip.length);
    const target = into ? `${into}/${relative}` : relative;
    await writeContents(await index.file(target), () => reader.stream(entry));
    // Counted outside the call: optional chaining would skip the increment
    // along with the callback, and `done` is this function's return value.
    done++;
    onProgress?.({ done, total: wanted.length, path: relative });
  });

  return done;
}

/** A file somewhere under the directory that was walked. */
export interface FoundFile {
  /** Path relative to where the walk started. */
  path: string;
  handle: FileSystemFileHandle;
}

/**
 * Every file under `path`, depth first. Empty when `path` is not there.
 *
 * Unlike `listPaths` this yields the handles, so the caller can read what it
 * found without resolving each path a second time.
 */
export async function listFiles(
  root: FileSystemDirectoryHandle,
  path = '',
): Promise<FoundFile[]> {
  const start = await directoryOf(root, path, false);
  if (!start) return [];

  const files: FoundFile[] = [];
  const walk = async (handle: FileSystemDirectoryHandle, prefix: string): Promise<void> => {
    for await (const [name, entry] of (handle as IterableDirectory).entries()) {
      const child = prefix ? `${prefix}/${name}` : name;
      if (entry.kind === 'directory') {
        await walk(entry as FileSystemDirectoryHandle, child);
      } else {
        files.push({ path: child, handle: entry as FileSystemFileHandle });
      }
    }
  };

  await walk(start, '');
  return files;
}

/** Every file under `path`, mapped to its size. Empty when `path` is not there. */
async function fileSizes(
  root: FileSystemDirectoryHandle,
  path: string,
): Promise<Map<string, number>> {
  const found = await listFiles(root, path);
  const sizes = new Map<string, number>();
  // `getFile()` is a round trip per file and there are ~1,240 of them on a
  // resumed copy, which is the only time this finds anything at all.
  await pooled(found, STAGE_CONCURRENCY, async ({ path: at, handle }) => {
    sizes.set(at, (await handle.getFile()).size);
  });
  return sizes;
}

/**
 * Copy a directory the player picked straight across.
 *
 * This is the path worth taking when the browser has `showDirectoryPicker`: no
 * archive to build on the player's side, and no inflate on ours.
 *
 * The copy is resumable: storage is indexed once up front and a file already
 * there at the same size is left alone. That matters because the alternative is
 * rewriting ~1.3 GB whenever a player hands the folder over again — after a
 * copy they interrupted, or one the page could not offer to resume. Size is a
 * weak identity, but the case it has to catch is the truncated file an aborted
 * write leaves behind, and it catches that.
 *
 * Returns the number of files actually written; `onProgress` counts every file
 * considered, so its `done`/`total` stays a real position in the work.
 */
export async function copyDirectoryInto(
  source: FileSystemDirectoryHandle,
  root: FileSystemDirectoryHandle,
  into = '',
  options: CopyOptions = {},
): Promise<number> {
  const { filter, onProgress } = options;
  const files = (await listFiles(source)).filter(({ path }) => (filter ? filter(path) : true));

  // One walk of the destination, rather than a lookup per file: on a fresh
  // install this finds nothing and costs nothing, and on a resumed one it is
  // what turns a thousand-odd writes into a thousand-odd map hits.
  const staged = await fileSizes(root, into);

  const index = new DirectoryIndex(root);
  let done = 0;
  let written = 0;

  await pooled(files, STAGE_CONCURRENCY, async ({ path, handle }) => {
    const file = await handle.getFile();
    if (staged.get(path) !== file.size) {
      const target = into ? `${into}/${path}` : path;
      await writeContents(
        await index.file(target),
        () => file.stream() as ReadableStream<Uint8Array>,
      );
      written++;
    }
    done++;
    onProgress?.({ done, total: files.length, path });
  });

  return written;
}

// ------------------------------------------------------------- staging, once --

/** Where an install is coming from. Both shapes survive `postMessage`. */
export type StageSource =
  | { kind: 'directory'; handle: FileSystemDirectoryHandle }
  | {
      kind: 'zip';
      archive: Blob | Uint8Array;
      /** The install root inside the archive, stripped off every entry. */
      strip: string;
    };

export interface StageRequest {
  root: FileSystemDirectoryHandle;
  source: StageSource;
  /** Write under this path inside `root` rather than at its top level. */
  into?: string;
  /**
   * Relative paths starting with one of these are not written.
   *
   * Prefixes rather than a predicate because this request crosses a
   * `postMessage` boundary, and a function does not.
   */
  skip?: readonly string[];
}

/**
 * Get an install into storage. The single entry point both realms share.
 *
 * `celeste.stage.worker.ts` calls this with the request handed to it, and
 * `stageWithWorker` calls it directly when there is no worker to be had — so
 * the two routes differ only in where they run, never in what they do.
 */
export async function stageInto(
  request: StageRequest,
  onProgress?: (progress: StageProgress) => void,
): Promise<number> {
  const { root, source, into = '', skip = [] } = request;
  const wanted = (path: string): boolean => !skip.some((prefix) => path.startsWith(prefix));

  if (source.kind === 'directory') {
    return copyDirectoryInto(source.handle, root, into, { filter: wanted, onProgress });
  }

  const reader = await ZipReader.open(source.archive);
  return extractInto(reader, root, { into, strip: source.strip, filter: wanted, onProgress });
}
